Description: >
  Developer Machine to connect with EKS.
Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${ID}
      GroupDescription: Allow port 22 and port 3030.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity-capstone
      ImageId: ami-0747bdcabd34c712a
      Tags:
        - Key: Name
          Value: !Sub ${ID}

Outputs:
  InstanceIP:
    Description: EC2 instance public IP
    Value: !GetAtt EC2Instance.PublicIp